### PR TITLE
Fix history.listen triggered by initial page load on some old browsers

### PR DESCRIPTION
**Pull request by yangmingshan**
Popstate event will fire after initial page load on some old browsers, like Safari on iOS 9. It will trigger history.listen.

This PR is a hack to fix this problem, the solution is from [page.js](https://github.com/visionmedia/page.js). I tested on iOS 9, it worked.

### CODE REVIEW

**Comment by yangmingshan** [comment]
I don't know why the Travis CI always timeout 😔

**Comment by mjackson** [comment]
Thanks for the PR, @yangmingshan. Is this code lifted directly from page.js? If so, I'd like to include a comment that tells people where we got it so we give attribution where it's due.

Would you mind rebasing on top of the current master?

**Comment by yangmingshan** [comment]
Rebased. And yes, this code is from page.js, you can find in [here](https://github.com/visionmedia/page.js/blob/master/index.js#L576-L600).

How I get the testing pass, is there something wrong？

**Comment by yangmingshan** [comment]
The solution source information added.

**Comment by danywheeler** [comment]
What's the status here? today I run into the same problem.

**Comment by yangmingshan** [comment]
@mjackson Can you look at it? It's been a long time.

**Comment by mjackson** [comment]
Sorry for the delay here. This will be released in 4.10.

**Comment by mjackson** [comment]
Hi @yangmingshan, I merged this but it causes one of our tests to fail on Firefox. You can see the failure here: https://travis-ci.org/ReactTraining/history/jobs/583498880

I'm going to revert the commit for now, but I'd be open to trying again if you can figure out what's going wrong in Firefox. Thanks!

**Pull request merged**
