### PR TITLE
Backport "Fix the back button in Chrome iOS" to v3.x

### PR DESCRIPTION
**Pull request by RocketPuppy**
See commit 822d72f4179e3e1892d31b3a571357d2ff8f36bf for original code in v4.x

See https://github.com/ReactTraining/history/pull/383 for the original code, and https://github.com/ReactTraining/react-router/issues/4365 for the instigating issue.

### CODE REVIEW

**Comment by Peterabsolon** [comment]
Please, please, please merge this :(

**Comment by mjackson** [comment]
Just a heads up that this is very low-priority for me. All my time these days is dedicated to working on history and React Router v4. If you really need it, please step up and become a maintainer.

**Comment by RocketPuppy** [comment]
@mjackson so what needs to be done to get this merged and released? Can I help speed that process along (without necessarily becoming a maintainer)? This bug is breaking our application for users using Chrome on iOS and we aren't ready to invest the time into upgrading to react router v4 where this is fixed until it's out of beta.

**Comment by mjackson** [comment]
Maintainers merge PRs and cut releases. If you don't want to be a maintainer then you need to find a maintainer who is willing to do it for you. I'm willing to do it, just saying that it's not high priority for me because I've got a lot on my plate right now. So I just wanted to set expectations.

**Comment by mjackson** [comment]
@djkirby Do you need some help?

**Comment by djkirby** [comment]
@mjackson sorry I didn't mean to push this here, will fix

**Comment by mjackson** [comment]
@djkirby No worries. Happy to provide guidance. Also, thanks for stepping up :)

**Comment by djkirby** [comment]
Ok I removed that commit. To clarify, I moved that commit to a separate branch, so @RocketPuppy and I can point our app to a forked version with this fix. 

Is there anything we can do in the meantime to help get this out the door? 😄

**Comment by mjackson** [comment]
Thanks for the PR. Apologies it took so long to get it merged. Will cut a release shortly.

**Comment by mjackson** [comment]
Published in 3.3.0. Thanks again :)

**Pull request merged**
