### PR TITLE
Added callback to history.replace().

### PR DESCRIPTION
**Pull request by StringEpsilon**
Implements the feature request made in #698, specifically the idea I explained in my comment there.

I'm not entirely sure if the callback should also be added to other actions. A maintainers input either here or on the original feature request is greatly appreciated.

(Also: I can undo the white-space changes, as they create quite a lot of noise. But it's actually more consistent now)

### CODE REVIEW

**Comment by mjackson** [comment]
I'm hesitant to add more API to this package, because it's already far too big. I think the root issue in #698 is that the location change happens asynchronously instead of synchronously like the browser does it. I think if we fix that (probably in a major bump) we can avoid adding more API to deal with the async behavior.

**Comment by StringEpsilon** [comment]
@mjackson: is there active work on a 5.0 version? The roadmap issue is locked, so I can't comment on there.

If 5.0 is on the horizon, that's great news (and I'll close this PR). But if it's still a while off then this feature might help to bridge the gap for those in need. We can still rip it out in 5.0 anyway, if we properly communicate that it's a temporary solution til synchronicity is restored.

**Comment by mjackson** [comment]
Everything on master is going into 5.0. I'm planning on releasing a beta this week. Just need to button up a few details. I'll update the roadmap.

**Comment by mjackson** [comment]
> Everything on master is going into 5.0. I'm planning on releasing a beta this week.

Scratch that. I'm working on 5.0 in the `dev` branch. Development on 4.x will continue on `master`.

**Pull request closed without merging**
