### PR TITLE
Normalize browsers that fire a popstate event on load

### PR DESCRIPTION
**Pull request by hydnhntr**
> Browsers tend to handle the popstate event differently on page load. Chrome (prior to v34) and Safari (prior to 10.0) always emit a popstate event on page load, but Firefox doesn't.

— [MDN: WindowEventHandlers.onpopstate](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate)

Modern browsers that fired `popstate` on load no longer do so. Yahoo’s [fluxible-router](https://github.com/yahoo/fluxible/tree/master/packages/fluxible-router) features a wrapper around the History Web API and [normalized this behaviour across browsers](https://github.com/yahoo/fluxible/issues/349) by suppressing the event.

I’m not sure about the placement of my new additions, feel free to advise how I could integrate them better.

As Safari/WebKit exhibited this quirk #511 might be solved with these changes.

### CODE REVIEW

**Comment by DevSide** [comment]
:+1:

**Comment by mjackson** [comment]
Can you please say more about why you need this? I don't want to call `replaceState` on the initial page load if we can avoid it. We should be able to initialize a history object using the current state of the world and not have to change it immediately to conform to our expectations.

**Comment by Ben07** [comment]
when would you merge this submit？I face the same problem

**Comment by danywheeler** [comment]
I do have this problem in IOS below 9.3, the popstate fires on page load.

**Comment by mjackson** [comment]
Closing due to lack of response from the OP.

**Pull request closed without merging**
