### PR TITLE
Fix History.createLocation definition in glossary

### PR DESCRIPTION
**Pull request by vslinko**

### CODE REVIEW

**Comment by taion** [comment]
@mjackson Are those extra 2 args supposed to be part of the public API? Seems like they shouldn't be.

**Comment by vslinko** [comment]
private args? this is something new 😀

**Comment by taion** [comment]
No, I mean... I don't see why those should be user-accessible. I feel like those args shouldn't be part of the API. I dunno.

**Comment by mjackson** [comment]
Yep, they're there right now so we may as well document them. They might not be there forever though.

**Pull request merged**
