### PR TITLE
Replace warning and invariant with tiny versions

### PR DESCRIPTION
**Pull request by TrySound**
`warning` and `invariant` packages are jealously maintained as mirrors
of fbjs versions. Guys do not accept optimizations like esm.

But happily there are alternatives. They are even more lightweight and
save for us 2kB of parsed (minified) code.

### CODE REVIEW

**Comment by TrySound** [comment]
@mjackson after this I will submit one more very nice improvement :)

**Comment by mjackson** [comment]
The build is broken. I'm trying to fix it now.

**Comment by TrySound** [comment]
Wait. I found one problem with them. Names are not provided and they are appear in bundle as `function index() {}`. Fixing.

**Comment by TrySound** [comment]
Ref
https://github.com/alexreardon/tiny-invariant/pull/15
https://github.com/alexreardon/tiny-warning/pull/1

**Comment by TrySound** [comment]
Done. Updated to latest versions.

**Comment by mjackson** [comment]
Thanks, @TrySound. This is good stuff. Makes me wanna do the same thing in all my repos!

**Pull request merged**
