### PR TITLE
[fixed] hash history trigger listeners twice when push a new location

### PR DESCRIPTION
**Pull request by Lucifier129**

### CODE REVIEW

**Comment by taion** [comment]
What is this supposed to do? The guard in `transitionTo` in `createHistory` already catches this. Your test case passes against master.

**Comment by Lucifier129** [comment]
@taion history.createHashHistory will trigger listeners twice when path is changed

```javascript
history.push('/test') // trigger listeners and modify location.hash 
hashchange handler // trigger listeners
```

`locationsAreEqual` at `transitionTo` can not detect this problem, because of the `key` is different between `nextLocation` and `currentLocation`.

**Comment by taion** [comment]
Which browser do you see this on?

**Comment by Lucifier129** [comment]
It is chrome 47.0.2526.73

**Comment by taion** [comment]
Can you push up a commit with just the test case and not your code change? I want to see the CI fail on that. The test ran successfully for me locally without the code change.

**Comment by Lucifier129** [comment]
OK

**Pull request closed without merging**
