### PR TITLE
add option to include origin in generated urls.

### PR DESCRIPTION
**Pull request by joeuy**
Add a config option to include origin in generated urls.

### CODE REVIEW

**Comment by mjackson** [comment]
Why do you need this?

**Comment by joeuy** [comment]
Hi, 
The justification for this change and discussion is coming from previous PR. 

> If you'd like to discuss a separate origin option, as @pshrmn suggested I'd be interested to hear that.
https://github.com/ReactTraining/history/pull/456#issuecomment-295810856

**Comment by mjackson** [comment]
Why can't you just `document.origin + history.createHref('/more/stuff')`? It doesn't seem like we need to give you API for this.

**Comment by joeuy** [comment]
The main reason I could think about is that browser history is in the business of creating urls, its better for clients to rely on history module which will abstract away any browser difference etc, and give you what you need. 

Also the main motivation for this is to use in react-router, and I was told to get the change done here first.

**Comment by joeuy** [comment]
@mjackson any comment?

**Comment by mjackson** [comment]
As I said in https://github.com/ReactTraining/history/pull/456#issuecomment-295810856 I'm really skeptical that you actually need this API and I'm fairly sure that including support for origin and/or domains at any level is just going to leak into other places in the API so we have to support it there as well. Unless you can show me a real use case that is really difficult for you right now I'm inclined to pass.

**Pull request closed without merging**
